#rustflags = ["-C", "linker=dylint-link"]
#[target.x86_64-unknown-linux-gnu]

[target.'cfg(all())']
linker = "dylint-link"

# For Rust versions 1.74.0 and onward, the following alternative can be used
# (see https://github.com/rust-lang/cargo/pull/12535):
# linker = "dylint-link"
